### ISSUE TITLE
Management - change user roles

### ISSUE THREAD

**Issue by kslysz** [databucket/databucket-server#85]
I'm trying to change super user. Set enabled all roles and save.

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "pl.databucket.server.entity.User.getEmail()" is null
        at pl.databucket.server.service.ManageUserService.modifyUser(ManageUserService.java:137)
        at pl.databucket.server.controller.ManageUserController.modifyUser(ManageUserController.java:66)
        at pl.databucket.server.controller.ManageUserController$$FastClassBySpringCGLIB$$9894c0bb.invoke(<generated>)

**Comment by kslysz** [comment]
fixed since 3.4.4
